### ISSUE TITLE
Error when running in visual studio

### ISSUE THREAD

**Issue by adeliab** [dotnet-architecture/eShopOnDapr#107]
I tried running the solution using visual studio and got this error

12>ERROR: for Web.Shopping.HttpAggregator  Cannot create container for service webshoppingagg: i/o timeout
12>ERROR: for catalog-api-dapr  b'i/o timeout'
12>ERROR: for webshoppingagg  Cannot create container for service webshoppingagg: i/o timeout
12>Encountered errors while bringing up the project.
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018: The "PrepareForLaunch" task failed unexpectedly.
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018: Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Error response from daemon: i/o timeout
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at Microsoft.Docker.DockerClient.<ExecuteAsync>d__0.MoveNext() in D:\a\_work\1\s\src\Microsoft.Docker\DockerClient.cs:line 26
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018: --- End of stack trace from previous location where exception was thrown ---
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at Microsoft.Docker.DockerClientExtensions.<GetServerOperatingSystemAsync>d__8.MoveNext() in D:\a\_work\1\s\src\Microsoft.Docker\DockerClientExtensions.cs:line 185
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018: --- End of stack trace from previous location where exception was thrown ---
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at Microsoft.Docker.Prerequisites.DockerTargetOSCheckPrerequisite.<EvaluateAsync>d__4.MoveNext() in D:\a\_work\1\s\src\Microsoft.Docker\Prerequisites\DockerTargetOSCheckPrerequisite.cs:line 42
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018: --- End of stack trace from previous location where exception was thrown ---
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at Microsoft.Docker.Prerequisites.DockerCompositePrerequisite.<EvaluateAsync>d__3.MoveNext() in D:\a\_work\1\s\src\Microsoft.Docker\Prerequisites\DockerCompositePrerequisite.cs:line 48
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018: --- End of stack trace from previous location where exception was thrown ---
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at Microsoft.Docker.BuildTasks.DockerBuildTask.<EvaluateBuildPrerequisitesAsync>d__35.MoveNext() in D:\a\_work\1\s\src\Microsoft.Docker.BuildTasks\DockerBuildTask.cs:line 120
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018: --- End of stack trace from previous location where exception was thrown ---
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() in D:\a\_work\1\s\src\Microsoft.Docker.BuildTasks\DockerBuildTask.cs:line 90
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018: --- End of stack trace from previous location where exception was thrown ---
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at Microsoft.Docker.BuildTasks.DockerBuildTask.Execute() in D:\a\_work\1\s\src\Microsoft.Docker.BuildTasks\DockerBuildTask.cs:line 73
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018: Error code: DT1005
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018: Severity: Error
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018: Command line: docker version --format {{.Server.Os}}
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018: Command exit code: 1
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018: Command output: 
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018: Command error: Error response from daemon: i/o timeout
12>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(399,5): error MSB4018:
12>Done building project "docker-compose.dcproj" -- FAILED.

**Comment by adeliab** [comment]
It works after closing VS and trying it again
