### ISSUE TITLE
Azure Container Apps Missing SecretStore

### ISSUE THREAD

**Issue by rmcaneny-cs** [dotnet-architecture/eShopOnDapr#120]
The following Apps are failing at startup for Azure Container Apps:
* Catalog API
* Identity API
* Ordering API
* (And of course the Aggregator because of the above).

It looks like you are missing some DAPR settings for the ACA implementation:

1. Identity API bicep needs to have DAPR wired in.
2.  dapr SecretStore is not being created in the Bicep files. This is causing the above to fail.

Thanks

Some additional information. Before and after creating a Secret store I get the following stack trace from identiy-api.
It appears that Dapr is loading and I see that the secretstore is loaded by the dapr component.

```
Unhandled exception. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Dapr.Client.DaprClientGrpc.WaitForSidecarAsync(CancellationToken cancellationToken)
   at Dapr.Extensions.Configuration.DaprSecretStore.DaprSecretStoreConfigurationProvider.LoadAsync()
   at Dapr.Extensions.Configuration.DaprSecretStore.DaprSecretStoreConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Dapr.Extensions.Configuration.DaprSecretStoreConfigurationExtensions.AddDaprSecretStore(IConfigurationBuilder configurationBuilder, String store, DaprClient client, IReadOnlyDictionary`2 metadata)
   at Microsoft.eShopOnDapr.Services.Identity.API.ProgramExtensions.AddCustomConfiguration(WebApplicationBuilder builder) in /src/src/Services/Identity/Identity.API/ProgramExtensions.cs:line 11
   at Program.<Main>$(String[] args) in /src/src/Services/Identity/Identity.API/Program.cs:line 4
   at Program.<Main>(String[] args)
```

**Comment by rmcaneny-cs** [comment]
Similar work being done around this:
https://github.com/dotnet-architecture/eShopOnDapr/issues/100
https://github.com/dotnet-architecture/eShopOnDapr/pull/115
