### ISSUE TITLE
How to generate migration files?

### ISSUE THREAD

**Issue by vosamo** [dotnet-architecture/eShopOnDapr#128]
Hi,I removed the db migration files in Migration directory,and I tried to generate new migration files with command "Add-Migration InitialMigration -verbose",but error occured.I don't know how to generate migration files successfully,can anyone give me a hand?

Error log as shown below:

PM> Add-Migration InitialMigration -verbose
Using project 'src\Services\Catalog\Catalog.API'.
Using startup project 'src\Services\Catalog\Catalog.API'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile D:\work\code\learn\dotnet\eShopOnDapr-20221229\eShopOnDapr-main\src\Services\Catalog\Catalog.API\bin\Debug\net6.0\Catalog.API.deps.json --additionalprobingpath C:\Users\nobody\.nuget\packages --additionalprobingpath "D:\Program Files\Microsoft Visual Studio\Shared\NuGetPackages" --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig D:\work\code\learn\dotnet\eShopOnDapr-20221229\eShopOnDapr-main\src\Services\Catalog\Catalog.API\bin\Debug\net6.0\Catalog.API.runtimeconfig.json C:\Users\nobody\.nuget\packages\microsoft.entityframeworkcore.tools\6.0.8\tools\netcoreapp2.0\any\ef.dll migrations add InitialMigration --json --verbose --no-color --prefix-output --assembly D:\work\code\learn\dotnet\eShopOnDapr-20221229\eShopOnDapr-main\src\Services\Catalog\Catalog.API\bin\Debug\net6.0\Catalog.API.dll --project D:\work\code\learn\dotnet\eShopOnDapr-20221229\eShopOnDapr-main\src\Services\Catalog\Catalog.API\Catalog.API.csproj --startup-assembly D:\work\code\learn\dotnet\eShopOnDapr-20221229\eShopOnDapr-main\src\Services\Catalog\Catalog.API\bin\Debug\net6.0\Catalog.API.dll --startup-project D:\work\code\learn\dotnet\eShopOnDapr-20221229\eShopOnDapr-main\src\Services\Catalog\Catalog.API\Catalog.API.csproj --project-dir D:\work\code\learn\dotnet\eShopOnDapr-20221229\eShopOnDapr-main\src\Services\Catalog\Catalog.API\ --language C# --configuration Debug --working-dir D:\work\code\learn\dotnet\eShopOnDapr-20221229\eShopOnDapr-main --root-namespace Microsoft.eShopOnDapr.Services.Catalog.API --nullable
Using assembly 'Catalog.API'.
Using startup assembly 'Catalog.API'.
Using application base 'D:\work\code\learn\dotnet\eShopOnDapr-20221229\eShopOnDapr-main\src\Services\Catalog\Catalog.API\bin\Debug\net6.0'.
Using working directory 'D:\work\code\learn\dotnet\eShopOnDapr-20221229\eShopOnDapr-main\src\Services\Catalog\Catalog.API'.
Using root namespace 'Microsoft.eShopOnDapr.Services.Catalog.API'.
Using project directory 'D:\work\code\learn\dotnet\eShopOnDapr-20221229\eShopOnDapr-main\src\Services\Catalog\Catalog.API\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'Catalog.API'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Dapr.Client.DaprClientGrpc.WaitForSidecarAsync(CancellationToken cancellationToken)
   at Dapr.Extensions.Configuration.DaprSecretStore.DaprSecretStoreConfigurationProvider.LoadAsync()
   at Dapr.Extensions.Configuration.DaprSecretStore.DaprSecretStoreConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Dapr.Extensions.Configuration.DaprSecretStoreConfigurationExtensions.AddDaprSecretStore(IConfigurationBuilder configurationBuilder, String store, DaprClient client, IReadOnlyDictionary`2 metadata)
   at Microsoft.eShopOnDapr.Services.Catalog.API.ProgramExtensions.AddCustomConfiguration(WebApplicationBuilder builder) in D:\work\code\learn\dotnet\eShopOnDapr-20221229\eShopOnDapr-main\src\Services\Catalog\Catalog.API\ProgramExtensions.cs:line 12
   at Program.<Main>$(String[] args) in D:\work\code\learn\dotnet\eShopOnDapr-20221229\eShopOnDapr-main\src\Services\Catalog\Catalog.API\Program.cs:line 4
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass10_0.<ResolveHostFactory>b__0(String[] args)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass13_0.<ResolveServiceProviderFactory>b__3(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromHosting(String[] args)
An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: A task was canceled.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'CatalogDbContext'.
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'CatalogDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[Microsoft.eShopOnDapr.Services.Catalog.API.Infrastructure.CatalogDbContext]' while attempting to activate 'Microsoft.eShopOnDapr.Services.Catalog.API.Infrastructure.CatalogDbContext'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass21_4.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass21_4.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to create an object of type 'CatalogDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

**Comment by erjain** [comment]
Hi @vosamo, below are the instructions to update the database using migration: 
Run the following commands in Package Manager Console (PMC):
Install-Package Microsoft.EntityFrameworkCore.Tools
Add-Migration InitialCreate
Update-Database

This installs the PMC tools for EF Core. 
The Add-Migration command scaffolds a migration to create the initial set of tables for the model. 
The Update-Database command creates the database and applies the new migration to it.

Or, alternatively, you can also retrieve the migration files for catalog.api here: https://github.com/dotnet-architecture/eShopOnDapr/tree/main/src/Services/Catalog/Catalog.API/Infrastructure/Migrations.

**Comment by erjain** [comment]
This issue can be closed, however, you can continue the conversation or reopen it in case of more queries.
