### ISSUE TITLE
An unhandled error has occurred. Reload

### ISSUE THREAD

**Issue by huangyingting** [dotnet-architecture/eShopOnDapr#85]
When running from locally with "docker-compose up", it shows "An unhandled error has occurred. Reload" after using demo user alice/bob to login. 

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: net_http_message_not_success_statuscode, 401, Unauthorized
System.Net.Http.HttpRequestException: net_http_message_not_success_statuscode, 401, Unauthorized
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__13`1[[Microsoft.eShopOnDapr.BlazorClient.Basket.BasketData, BlazorClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Microsoft.eShopOnDapr.BlazorClient.Basket.BasketClient.GetItemsAsync()
   at Microsoft.eShopOnDapr.BlazorClient.Basket.UserBasket.LoadAsync()
   at Microsoft.eShopOnDapr.BlazorClient.Shared.BasketLoader.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )

**Comment by luisgizirian** [comment]
I see the same behavior. Also launching `docker-compose  up -d --build`, locally.

**Comment by amolenk** [comment]
Fixed by #91
